config/routes.rb
Portal::Application.routes.draw do
  devise_for :users

  root 'home#index'

  resources :regforms, :salons, :users, :people, :departments, :apps, :roles
  resources :disccards, only: [:index]

  get 'admin' => 'home#admin'
  get 'anketa' => 'anketa#index'
  get 'phones' => 'people#index'

  post 'new_anketum' => 'anketa#create', as: :new_anketum
  delete 'anketa/:id' => 'anketa#destroy', as: :delete_anketa
  get 'anketa/:id' => 'anketa#show', as: :show_anketa

  get 'unlinkedregforms', to: 'linkregforms#index', as: :unlinkedregform
  post 'linkregform', to: 'linkregforms#link_regform', as: :linkregform

  get 'owners', to: 'cardowners#index', as: :owners
  get 'children', to: 'cardowners#children', as: :children

  resources :linkregforms do
    get :autocomplete_disccard_number, on: :collection
  end

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new
    if user.has_role? :admin
        can :manage, :all
    end
    if user.has_role? :dc_viewer
        can :read, Disccard
    end

    if user.has_role? :dc_viewer_birthdays
        can :manage, Cardowner
    end

    if user.has_role? :phones_editor
        can :manage, Person
        can :manage, Department
    end

    if user.has_role? :phones_viewer
        can :read, Person
    end

    #if user.has_role? :dc_viewer_child_birthdays
    #    can :children, Cardowner
    #end
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/anketa.rb
class Anketa < ActiveRecord::Base
  dragonfly_accessor :image
end

app/models/app.rb
class App < ActiveRecord::Base

  has_many :roles

end

app/models/assignment.rb
class Assignment < ActiveRecord::Base

  belongs_to :user
  belongs_to :role

end

app/models/cardowner.rb
class Cardowner < ActiveRecord::Base
  has_many :cardownerchildrens
  has_many :disccards
  has_one :emailcheckresult

  def full_name
    full_name = self.fam + ' ' + self.name + ' ' + self.otch
  end

end

app/models/cardownerchildren.rb
class Cardownerchildren < ActiveRecord::Base
  belongs_to :cardowner

end

app/models/channel.rb
class Channel < ActiveRecord::Base
  belongs_to :disccardowners

end

app/models/department.rb
class Department < ActiveRecord::Base

  has_many :people

  has_many :children, class_name: 'Department', foreign_key: 'department_id'
  belongs_to :parent, class_name: 'Department', foreign_key: 'department_id'

  scope :head_departments, -> { where(parent: nil) }

end

app/models/disccard.rb
class Disccard < ActiveRecord::Base
  has_many :regforms
  belongs_to :cardowner
  belongs_to :salon

  def full_card_name
    full_card_name = self.number + ' ' + self.client_name
  end

  scope :localcards, lambda { |user| where(salon_id: user.salons) }

end

app/models/emailcheckresult.rb
class Emailcheckresult < ActiveRecord::Base

  belongs_to :cardowner

end

app/models/link_user_to_salon.rb
class LinkUserToSalon < ActiveRecord::Base

  #belongs_to :salon
  #belongs_to :user
end

app/models/person.rb
class Person < ActiveRecord::Base

  belongs_to :department

  def full_name
    full_name = self.fam + ' ' + self.nam + ' ' + self.otch
  end

  def full_fio
    full_fio = self.fam + ' ' + self.nam.at(0) + '.' + self.otch.at(0) + '.'
  end

end

app/models/place.rb
class Place < ActiveRecord::Base
  belongs_to :cardowners

end

app/models/regform.rb
class Regform < ActiveRecord::Base
  dragonfly_accessor :image

  belongs_to :disccard
  belongs_to  :salon

  def process_barcode
    process_barcode = %x{"zbarimg" -D "#{self.image.path}"}.scan(/\d+/).second
  end

  def set_barcode
    self.barcode =  %x{"zbarimg" -D "#{self.image.path}"}.scan(/\d+/).second
  end

  def set_disccard
    self.disccard = Disccard.find_by_barcode(self.barcode)
  end

  #scope :unlinked, -> { where('disccard_id is null').where(salon_id: current_user.salons) }

  scope :allregforms, -> { where(weak_quality: 0) }

  scope :unlinked, lambda { |user| where('disccard_id is null').where(salon_id: user.salons).where(weak_quality: 0) }

end

app/models/role.rb
class Role < ActiveRecord::Base

  has_many :assignments
  has_many :users, :through => :assignments

  belongs_to :app

end

app/models/salon.rb
class Salon < ActiveRecord::Base

  has_many :disccards
  has_and_belongs_to_many :users

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :recoverable, :rememberable, :trackable

  has_and_belongs_to_many :salons

  has_many :assignments
  has_many :roles, :through => :assignments

  def has_role?(role_sym)
    roles.any? { |r| r.name.underscore.to_sym == role_sym }
  end
end

app/controllers/apps_controller.rb
class AppsController < ApplicationController
  load_and_authorize_resource
  before_action :authenticate_user!
  before_action :find_app, only: [:destroy, :edit, :update, :show]

  def index
    @apps = App.all
  end

  def show
  end

  def new
    @app = App.new
  end

  def create
    if App.create(app_params)
      redirect_to apps_path
    else
      render 'new'
    end
  end

  def update
    if @app.update(app_params)
      redirect_to apps_path
    else
      render 'edit'
    end
  end

  def edit
  end

  def destroy
    @app.delete
    redirect_to apps_path
  end

  private

  def app_params
    params.require(:app).permit(:nam, :url, :enabled, :admin_only, :hidden)
  end

  def find_app
    @app = App.find(params[:id])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!

  def index
    @apps = App.where(hidden: false)
    if not (current_user.has_role? :admin)
      @apps = @apps.where(admin_only: false)
    end
  end

  def admin
  end
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  load_and_authorize_resource
  before_action :authenticate_user!
  before_action :find_person, only: [:destroy, :edit, :update, :show]
  before_action :get_departments, only: [:edit, :new, :phones]

  def index
    @head_departments = Department.head_departments
  end

  def show
  end

  def new
    @person = Person.new
  end

  def create
    if Person.create(person_params)
      redirect_to people_path
    else
      render 'new'
    end
  end

  def update
    if @person.update(person_params)
      redirect_to people_path
    else
      render 'edit'
    end
  end

  def edit
  end

  def destroy
    @person.delete
    redirect_to people_path
  end

  private

  def person_params
    params.require(:person).permit(:fam, :nam, :otch, :cell_phone, :phone, :department_id, :position, :email, :sort_order)
  end

  def find_person
    @person = Person.find(params[:id])
  end

  def get_departments
    @departments = Department.all.order(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/people/_form.html.erb
<table>
  <tr>
    <td>
      <%= simple_form_for @person do |a| %>
        <%= a.input :fam, label: "Фамилия" %>
        <%= a.input :nam, label: "Имя" %>
        <%= a.input :otch, label: "Отчество" %>
        <%= a.input :position, label: "Должность" %>
        <%= a.input :phone, label: "Телефон" %>
        <%= a.input :cell_phone, label: "Моб.телефон" %>
        <%= a.input :email, label: "Email" %>
        <%= a.input :sort_order, label: "Сортировка" %>
        <%= a.input :department_id, collection: @departments, value_method: :id, label_method: :name %>
        <%= a.submit "Сохранить" %>
      <% end %>
    </td>
  </tr>
</table>

app/views/people/index.html.erb
<h2>Список сотрудников</h2>
<%= link_to("Новый сотрудник", new_person_path, class: "btn btn-primary btn-sm") %>
<%= link_to("Новое подразделение", new_department_path, class: "btn btn-primary btn-sm") %>
<table class="table table-bordered">
<thead>
  <th>ФИО</th>
  <th>Должность</th>
  <th>Телефон</th>
  <th>Email</th>
  <th></th>
</thead>
<tbody>
  <% @head_departments.order(:sort_order).each do |h| %>
    <tr>
      <td colspan="4">
        <div class="text-center"><strong><%= h.name + (' ' + h.phone) %></strong></div>
      </td>
      <td>
        <%= link_to edit_department_path(h) do %>
          <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
        <% end %>
      </td>
    </tr>
    <% h.children.order(:sort_order).each do |hc| %>
      <tr>
        <td colspan="4">
          <div class="text-center"><strong><%= hc.name + (' ' + hc.phone) %></strong>
          </div>
        </td>
        <td>
          <%= link_to edit_department_path(hc) do %>
            <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
          <% end %>
        </td>
      </tr>
    		<% hc.people.order(:sort_order, :fam, :nam, :otch).each do |a| %>
          <tr>
            <td><%= a.full_name %>
            <td><%= a.position %></td>
            <td><%= a.phone %></td>
            <td><%= a.email %></td>
            <td>
                <%= link_to edit_person_path(a) do %>
                  <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
                <% end %>
                <%= link_to edit_person_path(a) do %>
                  <span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
                <% end %>
            </td>
          </tr>
    		<% end %>
    <% end %>
  <% end %>
</tbody>
</table>


app/views/people/show.html.erb
<%= render 'form' %>