config/routes.rb
Portal::Application.routes.draw do
  devise_for :users

  root 'home#index'

  resources :regforms, :salons, :users, :people, :departments, :apps, :roles
  resources :disccards, only: [:index]

  get 'admin' => 'home#admin'
  get 'anketa' => 'anketa#index'
  get 'phones' => 'people#index'

  post 'new_anketum' => 'anketa#create', as: :new_anketum
  delete 'anketa/:id' => 'anketa#destroy', as: :delete_anketa
  get 'anketa/:id' => 'anketa#show', as: :show_anketa

  get 'unlinkedregforms', to: 'linkregforms#index', as: :unlinkedregform
  post 'linkregform', to: 'linkregforms#link_regform', as: :linkregform

  get 'owners', to: 'cardowners#index', as: :owners
  get 'children', to: 'cardowners#children', as: :children

  resources :linkregforms do
    get :autocomplete_disccard_number, on: :collection
  end

end

app/models/cardowner.rb
class Cardowner < ActiveRecord::Base
  has_many :cardownerchildrens
  has_many :disccards
  has_one :emailcheckresult

  def full_name
    full_name = self.fam + ' ' + self.name + ' ' + self.otch
  end

end

app/controllers/cardowners_controller.rb
class CardownersController < ApplicationController

  before_action :authenticate_user!
  load_and_authorize_resource
  before_action :find_cardowner, only: [:show]

  def index
    @start_date = Date.parse(params[:start_date]) if params[:start_date] != nil && params[:start_date] != ""
    @start_date = Date.today() if @start_date == nil

    @end_date = Date.parse(params[:end_date]) if params[:end_date] != nil && params[:end_date] != ""
    @end_date = Date.today()+1 if @end_date == nil

    @start_date_str = @start_date.strftime('%Y%m%d')
    @end_date_str = @end_date.strftime('%Y%m%d')

    @owners = Cardowner.joins(disccards: [salon: :users]).where(users: {id: current_user.id}).where('(
    DATEADD(yy,Year(?)-Year(date_of_birth),date_of_birth)>=?
    and DATEADD(yy,Year(?)-Year(date_of_birth),date_of_birth)<?
    )
    or (
    DATEADD(yy,Year(?)-Year(date_of_birth)+1,date_of_birth)>=?
    and DATEADD(yy,Year(?)-Year(date_of_birth)+1,date_of_birth)<?
  )',@start_date_str,@start_date_str,@start_date_str,@end_date_str,@start_date_str,@start_date_str,@start_date_str,@end_date_str).distinct.order(last_year_sum: :desc).paginate(page: params[:page])
  end

  def children

    @start_date = Date.parse(params[:start_date]) if params[:start_date] != nil && params[:start_date] != ""
    @start_date = Date.today() if @start_date == nil

    @end_date = Date.parse(params[:end_date]) if params[:end_date] != nil && params[:end_date] != ""
    @end_date = Date.today()+1 if @end_date == nil

    @start_date_str = @start_date.strftime('%Y%m%d')
    @end_date_str = @end_date.strftime('%Y%m%d')

    @owners = Cardownerchildren.joins(cardowner: {disccards: [salon: :users]}).where(users: {id: current_user.id}).where(['
(
    DATEADD(yy,Year(?)-Year(Cardownerchildren.date_of_birth),Cardownerchildren.date_of_birth)>=?
    and DATEADD(yy,Year(?)-Year(Cardownerchildren.date_of_birth),Cardownerchildren.date_of_birth)<?
    )
    or (
    DATEADD(yy,Year(?)-Year(Cardownerchildren.date_of_birth)+1,Cardownerchildren.date_of_birth)>=?
    and DATEADD(yy,Year(?)-Year(Cardownerchildren.date_of_birth)+1,Cardownerchildren.date_of_birth)<?
  )
    ',@start_date_str,@start_date_str,@start_date_str,@end_date_str,@start_date_str,@start_date_str,@start_date_str,@end_date_str]).order('cardowners.last_year_sum DESC').paginate(page: params[:page])

    @o = @owners.to_a.uniq

  end

end

app/views/cardowners/children.html.erb
<h2>Дисконтные карты</h2>
<ul class="nav nav-tabs">
  <li role="presentaion"><%= link_to("Все карты", disccards_path) %></li>
  <li role="presentaion"><%= link_to("Дни рождения клиентов", owners_path) %></li>
  <li role="presentaion" class="active"><%= link_to("Дни рождения детей", "#") %></li>
</ul>
<br>
<%= form_tag children_path, method: 'get' do %>
  <%= date_field_tag :start_date, params[:start_date] %>
  <%= date_field_tag :end_date, params[:end_date] %>
  <%= submit_tag 'Показать' %>
<% end %>
<p><%= "Всего: #{@owners.count}" %></p>
<table class="table table-bordered table-hover">
  <thead>
    <tr>
      <th>ФИО</th>
      <th>Тип карты</th>
      <th><small>Сумма<br>за<br>последний<br>год</small></th>
      <th><small>Чеков<br>за<br>последний<br>год</small></th>
      <th>Предпочтения</th>
      <th>Телефон</th>
      <th>Ребенок</th>
    </tr>
  </thead>
  <tbody>
    <% @o.each do |a| %>
    <tr <% if a.cardowner.dont_bother == true %>class="danger"<% end %>>
      <td><%= a.cardowner.full_name %></td>
      <td>
          <% a.cardowner.disccards.each do |d| %>
            <% if d.activity != true %><del><% end %><%= d.disccard_type %><% if d.activity != true %></del><% end %><br>
          <% end %>
      </td>
      <td><%= a.cardowner.last_year_sum %></td>
      <td><%= a.cardowner.last_year_docs %></td>
      <td>
        <% m=a.cardowner.preferable_brands.split(',') %>
        <% m.each do |t| %>
          <%= t %><br>
        <% end %>
        <% if a.cardowner.last_visit != nil %>
          <strong>Последний визит: <%= a.cardowner.last_visit.strftime('%d.%m.%Y') %></strong>
        <% end %>
      </td>
      <td><%= number_to_phone a.cardowner.cellphone %></td>
      <td><%= a.child_name %><br><%= a.date_of_birth.strftime("%d.%m.%Y") %></td>
    </tr>
    <% end %>
  </tbody>
</table>
<%= will_paginate @owners %>


app/views/cardowners/index.html.erb
<h2>Дисконтные карты</h2>
<ul class="nav nav-tabs">
  <li role="presentaion"><%= link_to("Все карты", disccards_path) %></li>
  <li role="presentaion" class="active"><%= link_to("Дни рождения клиентов", "#") %></li>
  <li role="presentaion"><%= link_to("Дни рождения детей", children_path) %></li>
</ul>
<br>
<%= form_tag owners_path, method: 'get' do %>
    <%= date_field_tag :start_date, params[:start_date] %>
    <%= date_field_tag :end_date, params[:end_date] %>
    <%= submit_tag 'Показать' %>
<% end %>
<p><%= "Всего: #{@owners.count}" %></p>
<table class="table table-bordered table-hover">
  <thead>
    <tr>
      <th>ФИО</th>
      <th>Дата рождения</th>
      <th>Тип карты</th>
      <th><small>Сумма<br>за<br>последний<br>год</small></th>
      <th><small>Чеков<br>за<br>последний<br>год</small></th>
      <th>Предпочтения</th>
      <th>Телефон</th>
    </tr>
  </thead>
  <tbody>
    <% @owners.each do |a| %>
    <tr <% if a.dont_bother == true %>class="danger"<% end %>>
      <td><%= a.full_name %></td>
      <td><%= a.date_of_birth.strftime("%d.%m.%Y") %></td>
      <td>
          <% a.disccards.each do |d| %>
            <% if d.activity != true %><del><% end %><%= d.disccard_type %><% if d.activity != true %></del><% end %><br>
          <% end %>
      </td>
      <td><%= a.last_year_sum %></td>
      <td><%= a.last_year_docs %></td>
      <td>
        <% m=a.preferable_brands.split(',') %>
        <% m.each do |t| %>
          <%= t %><br>
        <% end %>
        <% if a.last_visit != nil %>
          <strong>Последний визит: <%= a.last_visit.strftime('%d.%m.%Y') %></strong>
        <% end %>
      </td>
      <td><%= number_to_phone a.cellphone %></td>
    </tr>
    <% end %>
  </tbody>
</table>
<%= will_paginate @owners %>
